name: First Workflow
on: [push ,workflow_dispatch]
jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code            # allow to downloading the code
        uses: actions/checkout@v4
        
      - name: Install Node.js         #allow to downloading the node  js
        uses: actions/setup-node@v4
        with:
         node-version: '20'
         
      - name: Check Node version               # verfication of node 
        run: node -v
      
        
