name: First Workflow
on: [push ,workflow_dispatch]

jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code    # allow to downloading code 
        uses: actions/checkout@v4
      - name: Insatll node js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'    # you must have package lock json 
      - name: Install Dependencies
        run: npm install 
      - name: Run build
        run: npm run build
      - name: uplaod Artifact
        uses: actions/upload-artifact@v4
        with:
          name: producion-files
          path: dist/

      - name: test code 
        run: npm test

      
        
