name: my second workflow

on: 
 push:
 workflow_dispatch:
 
jobs :  
  hello-jobs:
     runs-on: ubuntu-latest
     
     steps:
        - name:  Say hello
          run: echo "hello  , github actions"
          
        - name: Show the date 
          run: date 
   
 
